### ISSUE TITLE
Error: E117: Unknown function: minimap#ShowMinimap

### ISSUE THREAD

**Issue by eiger3970** [severin-lemaignan/vim-minimap#33] opened 2015-09-08 21:23 UTC
Hello, I installed Minimap on Vim, but all 3 Minimap versions have errors?

Vim 7.4.52:

1.
Minimap https://github.com/severin-lemaignan/vim-minimap
Installed the below code into Vundle in ~/.vimrc > run with command $ vim fileName.xyz > :Minimap > Error: E117: Unknown function: minimap#ShowMinimap

------------------------------------------------------------------------------
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" The following are examples of different formats supported.
" Keep Plugin commands between vundle#begin/end.

" git repos on your local machine (i.e. when working on your own plugin)
" 20150908: I commented this plugin as error.
" Plugin 'file:///home/gmarik/path/to/plugin'

" Git plugin not hosted on GitHub
Plugin 'git://git.wincent.com/command-t.git'

" plugin from http://vim-scripts.org/vim/scripts.html
Plugin 'L9'

" The sparkup vim script is in a subdirectory of this repo called vim.
" Pass the path to set the runtimepath properly.
Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}

" plugin for minimap/codeoverview.
Plugin 'severin-lemaignan/vim-minimap'

" plugin on GitHub repo
Plugin 'tpope/vim-fugitive'

" Avoid a name conflict with L9
" 20150908: I commented this plugin as error logging into my github account. 
" Plugin 'user/L9', {'name': 'newL9'}

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just
" :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to
" auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

filetype plugin indent on " Turns on matching tags.
syntax on " Turns on syntax colours all the time.
----------------------------------------------------------------

Gvim (needed for these 2 Minimaps).

2.
http://www.vim.org/scripts/script.php?script_id=2888
Installed in ~/.vim/bundle/vim-codeoverview/CodeOverview.vim
Run with command $ gvim fileName > :ShowCodeOverview > Error: E492: Not an editor command: ShowCodeOverview

3.
https://github.com/koron/minimap-vim
I installed the directories to ~/.vim
Run command $ gvim fileName > :e /path/to/file/fileName.xyz > Enter > :MinimapSync > works!
(It's a bit tedious entering the :e /path/to/file/fileName.xyz, as I have already navigated and opended the file using command /path/to/file $ gvim fileName.xyz.

**Comment by severin-lemaignan** [comment] 2015-10-11 20:04
Could you post the result of typing in vim the command?
```
:python import sys;print(sys.version)
```

**Comment by eiger3970** [comment] 2015-10-11 21:44
Hello, thank you for your reply.
The output is:
File "<string>", line 1
  import sys:print(sys.version)
                  ^
SyntaxError: invalid syntax

**Comment by severin-lemaignan** [comment] 2015-10-11 22:16
Yes... it looks like your vim does not support python extensions... you need to install/compile a vim with support for python.

Since the issue is not related to vim-minimap per se, I close the issue for now. Feel free to re-open if you think the issue is really with vim-minimap.

**Comment by eiger3970** [comment] 2015-10-12 01:27
Thanks. I updated the colon to a semi-colon. This should not affect the issue, as this is the output of the error.
I'm still looking for how to install Python to run with Vim. (if that's what I'm supposed to do).

**Comment by severin-lemaignan** [comment] 2015-10-12 08:15
Well, on Ubuntu or the like, `sudo apt-get install vim-nox` is what you are looking for.

**Comment by eiger3970** [comment] 2015-10-12 10:04
Thanks, I ran that command, but :Minimap shows the following error:
Error detected while processing function minimap#ShowMinimap:
line 8:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/.vim/bundle/vim-minimap/autoload/minimap.py", line 75, in showminimap
    vim.command(":call minimap#UpdateMinimap()")
vim.error: Vim(python):Traceback (most recent call last):

**Comment by severin-lemaignan** [comment] 2015-10-12 10:42
Could you post the whole traceback?

**Comment by eiger3970** [comment] 2015-10-12 11:42
Hello, I'm sorry however I don't know what you mean by the whole traceback?

What I provided above is everything. The next line (the bottom line) says:
Press ENTER or type command to continue.

**Comment by severin-lemaignan** [comment] 2015-10-12 11:56
You can try this:
```
vim file.tex &> errors.log
```
The full trace *should* be in `errors.log`

**Comment by eiger3970** [comment] 2015-10-12 23:43
Thanks. My Linux Mint 17.1 OS doesn't have any /var/log/errors.log.
$ sudo vim index.html &> errros.log
bash: errors.log: Permission denied.

I'll have to look at this another time as I'm out of time for the moment.

**Comment by severin-lemaignan** [comment] 2015-10-13 08:27
Since this error is likely due to an incorrect setup, I close the issue for now. Please re-open it if you believe it is really a `vim-minimap` problem.

**Closed by severin-lemaignan** 2015-10-13 08:27 UTC
